### ISSUE TITLE
Crash on qt project compilation

### ISSUE THREAD

**Issue by mehelme** [enferex/spellhell#3]
When compiling http://doc.qt.io/qt-5/qtwidgets-widgets-calculator-example.html the plugin crash:
```
Event                            | Plugins
PLUGIN_ALL_IPA_PASSES_START      | spellhell
moc_calculator.cpp:168:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugs.opensuse.org/> for instructions.
Makefile:515: recipe for target 'moc_calculator.o' failed
make: *** [moc_calculator.o] Error 1

```
opensuse 42 64 bit, qt5.6.1, gcc-6 (SUSE Linux) 6.3.1 20170202 [gcc-6-branch revision 245119]
also crased on ubuntu 14.04 64 bit (gcc-5)

as i put some printf in spellhell.c and seems crashing somethere in is_str_cst(op)
this is my fist gcc plugin i ever used, so not well gcc inside knowledge

also make test - works fine

**Comment by enferex** [comment]
@mehelme Thanks for the feedback!  I can take a peek at this tonight or later this week.

**Comment by enferex** [comment]
@mehelme I updated the string constant routine.  I did not test agaisnt the code example (moc_calculator.cpp) I didn't see it in the QT 5.8.0 code base, but I did find a copy via google.  Let me know if the version here is any better:
https://github.com/enferex/spellhell/tree/fix_oops_with_qt

**Comment by mehelme** [comment]
@enferex thanks, i testes it but now crash on second call to FOR_EACH_BB_FN(bb, fn), as i saw my added printf: 
```
fprintf(stderr, "%i\n", __LINE__);
        FOR_EACH_BB_FN(bb, fn)
        {
fprintf(stderr, "%i\n", __LINE__);

```
i created rep with calc example src [https://github.com/mehelme/spellhell](url)
0.sh is compile cmd of the moc_calculator.cpp

**Comment by enferex** [comment]
Thanks for the fork.  I was able to recreate and fix the bug.  Test out the updated changes:
https://github.com/enferex/spellhell/tree/fix_oops_with_qt

**Comment by mehelme** [comment]
Yes, this update fixed crashes !
