### ISSUE TITLE
Debug outputon qt project

### ISSUE THREAD

**Issue by mehelme** [enferex/spellhell#4]
Hi !

I build plugin (on branch fix_oops_with_qt) with -DDEBUG macro to see strings, then do **make test** - this works ok.
But then i try to build qt project (same calculator example), i got some output errors
See https://github.com/mehelme/spellhell/blob/master/0.sh,  
and output https://github.com/mehelme/spellhell/blob/master/calculator_build_log.txt

**Comment by enferex** [comment]
This looks like an error in your build line.  Try removing the '-pipe' flag OR avoid using the shell redirection.

**Comment by mehelme** [comment]
If i remove **-fplugin=./spellhell.so** the build is completed ok
If i remove **-pipe** the build is also completed ok
But **-pipe** is added by qmake, so it valid switch
I try to use output to stderr: **fprintf(stderr, "Spell checking string: %s\n", data);** and it works ok
So issue may be completed with this fix.
